src/main/java/com/divudi/bean/common/CreditCompanyController.java
/*
 * MSc(Biomedical Informatics) Project
 *
 * Development and Implementation of a Web-based Combined Data Repository of
 Genealogical, Clinical, Laboratory and Genetic Data
 * and
 * a Set of Related Tools
 */
package com.divudi.bean.common;

import com.divudi.data.InstitutionType;
import com.divudi.entity.Category;
import com.divudi.entity.Institution;
import com.divudi.entity.Item;
import com.divudi.facade.InstitutionFacade;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.ejb.EJB;
import javax.enterprise.context.SessionScoped;
import javax.inject.Inject;
import javax.inject.Named;

/**
 *
 * @author Dr. M. H. B. Ariyaratne, MBBS, PGIM Trainee for MSc(Biomedical
 * Informatics)
 */
@Named
@SessionScoped
public class CreditCompanyController implements Serializable {

    private static final long serialVersionUID = 1L;
    @Inject
    SessionController sessionController;
    @Inject
    CommonController commonController;
    @EJB
    private InstitutionFacade ejbFacade;
    List<Institution> selectedItems;
    private Institution current;
    Item service;
    Category category;
    InstitutionType institutionType;

    private List<Institution> items = null;
    List<Institution> institutions;
    String selectText = "";

    public List<Institution> completeCredit(String query) {
        List<Institution> suggestions;
        String sql;
        if (query == null) {
            suggestions = new ArrayList<>();
        } else {
            sql = "select p from Institution p where p.retired=false and p.institutionType=com.divudi.data.InstitutionType.CreditCompany and upper(p.name) like '%" + query.toUpperCase() + "%' order by p.name";
            ////System.out.println(sql);
            suggestions = getFacade().findBySQL(sql);
        }
        return suggestions;
    }

    public List<Institution> getCreditCompanies() {
        String sql;
        sql = "select p from Institution p where p.retired=false and p.institutionType=com.divudi.data.InstitutionType.CreditCompany order by p.name";
        return getFacade().findBySQL(sql);
    }

    public List<Institution> getSelectedItems() {
        selectedItems = getFacade().findBySQL("select c from Institution c where c.retired=false and i.institutionType = com.divudi.data.InstitutionType.CreditCompany  and upper(c.name) like '%" + getSelectText().toUpperCase() + "%' order by c.name");
        return selectedItems;
    }

    public void prepareAdd() {
        current = new Institution();
        current.setInstitutionType(InstitutionType.CreditCompany);
    }

    public void setSelectedItems(List<Institution> selectedItems) {
        this.selectedItems = selectedItems;
    }

    public String getSelectText() {
        return selectText;
    }

    public List<Institution> getInstitutions() {
        return institutions;
    }

    public void setInstitutions(List<Institution> institutions) {
        this.institutions = institutions;
    }

    public Item getService() {
        return service;
    }

    public void setService(Item service) {
        this.service = service;
    }

    public Category getCategory() {
        return category;
    }

    public void setCategory(Category category) {
        this.category = category;
    }

    private void recreateModel() {
        items = null;
    }

    public void saveSelected() {

        if (getCurrent().getId() != null && getCurrent().getId() > 0) {
            getFacade().edit(current);
            UtilityController.addSuccessMessage("Updated Successfully.");
        } else {
            current.setCreatedAt(new Date());
            current.setCreater(getSessionController().getLoggedUser());
            getFacade().create(current);
            UtilityController.addSuccessMessage("Saved Successfully");
        }
        recreateModel();
        getItems();
    }

    public void fillCreditCompany() {
        Date startTime = new Date();
        Date fromDate = null;
        Date toDate = null;

        String sql = "select i from Institution i "
                + "where i.retired=false ";
        institutions = getEjbFacade().findBySQL(sql);

        commonController.printReportDetails(fromDate, toDate, startTime, "Reports/Check Entered Data/Credit Company/credit card companies(/faces/dataAdmin/credit_companies.xhtml)");
    }

    public void fillInstitutions() {

        String sql;
        Map m=new HashMap();
        
        sql= "select i from Institution i "
                + " where i.retired=false ";
        
        if (institutionType != null) {
            sql += " and i.institutionType=:insT";
            m.put("insT", institutionType);
        }
        
        institutions = getEjbFacade().findBySQL(sql,m);

    }

    public void setSelectText(String selectText) {
        this.selectText = selectText;
    }

    public InstitutionFacade getEjbFacade() {
        return ejbFacade;
    }

    public void setEjbFacade(InstitutionFacade ejbFacade) {
        this.ejbFacade = ejbFacade;
    }

    public SessionController getSessionController() {
        return sessionController;
    }

    public void setSessionController(SessionController sessionController) {
        this.sessionController = sessionController;
    }

    public CreditCompanyController() {
    }

    public Institution getCurrent() {
        if (current == null) {
            current = new Institution();
            current.setInstitutionType(InstitutionType.CreditCompany);
        }
        return current;
    }

    public void setCurrent(Institution current) {
        this.current = current;
    }

    public void delete() {

        if (current != null) {
            current.setRetired(true);
            current.setRetiredAt(new Date());
            current.setRetirer(getSessionController().getLoggedUser());
            getFacade().edit(current);
            UtilityController.addSuccessMessage("Deleted Successfully");
        } else {
            UtilityController.addSuccessMessage("Nothing to Delete");
        }
        recreateModel();
        getItems();
        current = null;
        getCurrent();
    }

    private InstitutionFacade getFacade() {
        return ejbFacade;
    }

    public List<Institution> getItems() {
        if (items == null) {
            String sql = "SELECT i FROM Institution i where i.retired=false and i.institutionType = com.divudi.data.InstitutionType.CreditCompany order by i.name";
            items = getEjbFacade().findBySQL(sql);
        }
        return items;
    }

    public CommonController getCommonController() {
        return commonController;
    }

    public void setCommonController(CommonController commonController) {
        this.commonController = commonController;
    }

    public InstitutionType getInstitutionType() {
        return institutionType;
    }

    public void setInstitutionType(InstitutionType institutionType) {
        this.institutionType = institutionType;
    }

    /**
     *
     */
}

src/main/java/com/divudi/bean/lab/LabBillCollectingController.java
/*
 * MSc(Biomedical Informatics) Project
 *
 * Development and Implementation of a Web-based Combined Data Repository of
 Genealogical, Clinical, Laboratory and Genetic Data
 * and
 * a Set of Related Tools
 */
package com.divudi.bean.lab;

import com.divudi.bean.common.BillBeanController;
import com.divudi.bean.common.SessionController;
import com.divudi.bean.common.UtilityController;
import com.divudi.data.BillClassType;
import com.divudi.data.BillNumberSuffix;
import com.divudi.data.BillType;
import com.divudi.data.PaymentMethod;
import com.divudi.data.Sex;
import com.divudi.data.Title;
import com.divudi.data.dataStructure.YearMonthDay;
import com.divudi.ejb.BillNumberGenerator;
import com.divudi.ejb.CommonFunctions;
import com.divudi.entity.Bill;
import com.divudi.entity.BillComponent;
import com.divudi.entity.BillEntry;
import com.divudi.entity.BillFee;
import com.divudi.entity.BillItem;
import com.divudi.entity.BilledBill;
import com.divudi.entity.Department;
import com.divudi.entity.Doctor;
import com.divudi.entity.Institution;
import com.divudi.entity.Patient;
import com.divudi.entity.PaymentScheme;
import com.divudi.entity.Person;
import com.divudi.entity.Staff;
import com.divudi.entity.lab.Investigation;
import com.divudi.entity.lab.PatientInvestigation;
import com.divudi.facade.BillComponentFacade;
import com.divudi.facade.BillFacade;
import com.divudi.facade.BillFeeFacade;
import com.divudi.facade.BillItemFacade;
import com.divudi.facade.PatientFacade;
import com.divudi.facade.PatientInvestigationFacade;
import com.divudi.facade.PersonFacade;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Objects;
import java.util.Set;
import javax.ejb.EJB;
import javax.enterprise.context.SessionScoped;
import javax.faces.component.UIComponent;
import javax.faces.context.FacesContext;
import javax.faces.convert.Converter;
import javax.faces.convert.FacesConverter;
import javax.inject.Inject;
import javax.inject.Named;
import org.primefaces.event.TabChangeEvent;

/**
 *
 * @author Dr. M. H. B. Ariyaratne, MBBS, PGIM Trainee for MSc(Biomedical
 * Informatics)
 */
@Named
@SessionScoped
public class LabBillCollectingController implements Serializable {

    BilledBill current;
    private static final long serialVersionUID = 1L;
    @Inject
    SessionController sessionController;
    @EJB
    private BillFacade billFacade;
    @EJB
    private BillItemFacade billItemFacade;
    private boolean printPreview;
    private String patientTabId = "tabNewPt";
    private YearMonthDay yearMonthDay;
    private PaymentScheme paymentScheme;
    private Patient newPatient;
    private Patient searchedPatient;
    private Doctor referredBy;
    //  private Institution creditCompany;
    private Institution collectingCentre;
    private Staff staff;
    private double total;
    private double discount;
    private double netTotal;
    double vatPlusNetTotal;
    double vat;
    private double cashPaid;
    private double cashBalance;
    private String creditCardRefNo;
    private String chequeRefNo;
    private Institution chequeBank;
    private BillItem currentBillItem;
    //Bill Items
    private List<BillComponent> lstBillComponents;
    private List<BillFee> lstBillFees;
    private List<BillItem> lstBillItems;
    private List<BillEntry> lstBillEntries;
    private Integer index;
    @EJB
    private PatientInvestigationFacade patientInvestigationFacade;
    @Inject
    private BillBeanController billBean;
    @EJB
    CommonFunctions commonFunctions;
    @EJB
    private PersonFacade personFacade;
    @EJB
    private PatientFacade patientFacade;
    @EJB
    private BillNumberGenerator billNumberBean;
    @EJB
    private BillComponentFacade billComponentFacade;
    @EJB
    private BillFeeFacade billFeeFacade;
    //Temprory Variable
    private Patient tmpPatient;

    public void dateChangeListen() {
        getNewPatient().getPerson().setDob(getCommonFunctions().guessDob(yearMonthDay));

    }

    public BilledBill getCurrent() {
        return current;
    }

    public void setCurrent(BilledBill current) {
        this.current = current;
    }

    public Title[] getTitle() {
        return Title.values();
    }

    public Sex[] getSex() {
        return Sex.values();
    }

    private void clearBillValues() {
        setNewPatient(null);
        setSearchedPatient(null);
        setReferredBy(null);
//        setCreditCompany(null);
        setYearMonthDay(null);
        setChequeBank(null);
        setPaymentScheme(null);
        setChequeRefNo("");
        setCreditCardRefNo("");
        currentBillItem = null;
        setLstBillComponents(null);
        setLstBillEntries(null);
        setLstBillFees(null);
        setStaff(null);
        lstBillEntries = new ArrayList<>();
        calTotals();
        setCashPaid(0.0);
        setDiscount(0.0);
        setCashBalance(0.0);
        patientTabId = "tabNewPt";
        current = new BilledBill();
    }

    public CommonFunctions getCommonFunctions() {
        return commonFunctions;
    }

    public void setCommonFunctions(CommonFunctions commonFunctions) {
        this.commonFunctions = commonFunctions;
    }

    private void savePatient() {
        if (getPatientTabId().equals("tabNewPt")) {
            getNewPatient().setCreater(getSessionController().getLoggedUser());
            getNewPatient().setCreatedAt(new Date());

            getNewPatient().getPerson().setCreater(getSessionController().getLoggedUser());
            getNewPatient().getPerson().setCreatedAt(new Date());

            getPersonFacade().create(getNewPatient().getPerson());
            getPatientFacade().create(getNewPatient());
            tmpPatient = getNewPatient();

        } else if (getPatientTabId().equals("tabSearchPt")) {
            tmpPatient = getSearchedPatient();
        }
    }

    public void putToBills() {
        Set<Department> billDepts = new HashSet<Department>();
        //List<Bill> bills = new ArrayList<Bill>();
        for (BillEntry e : lstBillEntries) {
            billDepts.add(e.getBillItem().getItem().getDepartment());
        }
        for (Department d : billDepts) {
            BilledBill myBill = new BilledBill();
            saveBill(d, myBill);
            bills.add(myBill);
            List<BillItem> list = new ArrayList<>();
            for (BillEntry e : lstBillEntries) {
                if (Objects.equals(e.getBillItem().getItem().getDepartment().getId(), d.getId())) {
                    //e.setBill(myBill);
                    myBill.getBillItems().add(saveBillItem(myBill, e));
                    calculateBillItem(myBill, e);
                }

                billFacade.edit(myBill);
            }
            //set Bill Item Properties like bill TOtal, Discount
            //Save Bill
        }

//        for (Bill myBill : bills) {
//            for (BillEntry e : lstBillEntries) {
//                if (e.getBill() == myBill) {
//                    ///Save Bill Items
//                }
//            }
//            // Save Bill Changes
//        }
    }

    private int checkDepartment() {

        int c = 0;
        Department tdep = new Department();
        tdep.setId(0L);
        // ////System.out.println("Check Dept 1 " + c);
        //Createa a list of bills
        for (BillEntry be : getLstBillEntries()) {
            if (be.getBillItem().getItem().getDepartment().getId() != tdep.getId()) {
                tdep = be.getBillItem().getItem().getDepartment();
                c++;
                //  ////System.out.println("Check Dept  " + be.getBillItem().getItem().getDepartment().getName());
            }
        }
        ////System.out.println("Check Dept 4 " + c);

        return c;
    }

    List<Bill> bills;

    public List<Bill> getBills() {
        return bills;
    }

    public void setBills(List<Bill> bills) {
        this.bills = bills;
    }

    public void settleBill() {
        if (errorCheck()) {
            return;
        }

        bills = new ArrayList<>();

        savePatient();
        if (checkDepartment() == 1) {
            current = new BilledBill();
            Bill b = saveBill(lstBillEntries.get(0).getBillItem().getItem().getDepartment(), current);

            b.setBillItems(saveBillItems(b));
            billFacade.edit(b);
            calculateBillItems(b);
            bills.add(b);
        } else {
            putToBills();
        }

        UtilityController.addSuccessMessage("Bill Saved");
        printPreview = true;
    }

    private void calculateBillItem(Bill bill, BillEntry e) {
        double s = 0.0;
        double i = 0.0;
        double g = 0.0;
        for (BillFee bf : e.getLstBillFees()) {
            g = g + bf.getFee().getFee();
            if (bf.getFee().getStaff() == null) {
                i = i + bf.getFeeValue();
            } else {
                s = s + bf.getFeeValue();
            }
            if (bf.getId() == null || bf.getId() == 0) {
                getBillFeeFacade().create(bf);
            } else {
                getBillFeeFacade().edit(bf);
            }
        }

        bill.setStaffFee(s);
        bill.setPerformInstitutionFee(i);
        bill.setTotal(g);
        bill.setNetTotal(g);
        getFacade().edit(bill);
    }

    private void calculateBillItems(Bill bill) {
        double s = 0.0;
        double i = 0.0;
        double g = 0.0;
        for (BillEntry e : getLstBillEntries()) {
            for (BillFee bf : e.getLstBillFees()) {
                g = g + bf.getFee().getFee();
                if (bf.getFee().getStaff() == null) {
                    i = i + bf.getFeeValue();
                } else {
                    s = s + bf.getFeeValue();
                }
                if (bf.getId() == null || bf.getId() == 0) {
                    getBillFeeFacade().create(bf);
                } else {

src/main/webapp/lab/search_for_reporting_to_dataenter.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:p="http://primefaces.org/ui"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core">

    <h:body>
        <ui:composition template="/resources/template/template.xhtml">
            <ui:define name="content">
                <h:form>
                    <p:panel header="Search Bills" >
                        <f:facet name="header">
                            <h:panelGrid columns="6" >
                                <h:outputLabel value="From Date"/>
                                <p:calendar styleClass="dateTimePicker" id="fromDate" value="#{searchController.fromDate}" navigator="false" pattern="dd MMMM yyyy hh mm ss a" >      
                                </p:calendar>
                                <h:outputLabel value="To Date"/>
                                <p:calendar id="toDate" value="#{searchController.toDate}" navigator="false" pattern="dd MMMM yyyy hh mm ss a" >                                                                              
                                </p:calendar>
                                <p:commandButton id="btnSearch" ajax="false" value="Search" action="#{searchController.createPatientInvestigationsTable()}"/>
                                <p:commandButton id="btnSearch2" ajax="false" value="Search All" action="#{searchController.createPatientInvestigationsTableAll()}"/>
                                <p:spacer height="30"/><h:outputLabel/>
                                <h:outputLabel/><h:outputLabel/>
                                <h:outputLabel/> <h:outputLabel/>

                                <h:outputLabel value="Bill No"/>
                                <h:outputLabel value="Patient Name"/>
                                <h:outputLabel value="Patient Phone"/>                               
                                <h:outputLabel value="Investigation Value"/>
                                <h:outputLabel/><h:outputLabel/>
                                <p:inputText autocomplete="off"  value="#{searchController.searchKeyword.billNo}" />
                                <p:inputText autocomplete="off" value="#{searchController.searchKeyword.patientName}" />
                                <p:inputText autocomplete="off"  value="#{searchController.searchKeyword.patientPhone}" />
                                <p:inputText autocomplete="off" value="#{searchController.searchKeyword.itemName}"/>

                            </h:panelGrid>
                        </f:facet>
                        <p:defaultCommand target="btnSearch" />

                        <p:dataTable  id="tblBills" value="#{searchController.patientInvestigations}" var="pi"  >

                            <p:column headerText="Billing" styleClass="alignTop" >
                                <h:outputLabel value="Bill No : #{pi.billItem.bill.insId}" ></h:outputLabel>
                                <br/>
                                <h:outputLabel value="Name : #{pi.billItem.bill.patient.person.nameWithTitle}" >
                                </h:outputLabel>
                                <br/>
                                <h:commandLink value="(edit)" action="patient" style="text-decoration:underline;" >
                                    <f:setPropertyActionListener value="#{pi.billItem.bill.patient}" target="#{patientController.current}"/>
                                </h:commandLink>
                                <br/>
                                <h:outputLabel value="Age : #{pi.billItem.bill.patient.age},&nbsp;#{pi.billItem.bill.patient.person.sex}," >
                                </h:outputLabel>
                                <br/>
                                <h:outputLabel value="Phone : #{pi.billItem.bill.patient.person.phone}" >
                                </h:outputLabel>
                                <br/>
                                <h:outputLabel value="Billed From : #{pi.billItem.bill.institution.name}" ></h:outputLabel>
                            </p:column>

                            <p:column headerText="Investigation"  styleClass="alignTop" >
                                <h:outputLabel value="Ix : #{pi.billItem.item.name}" >
                                </h:outputLabel>
                                <br/>
                                <h:outputLabel value="Billed : " />
                                <h:outputLabel value="#{pi.billItem.bill.createdAt}" >
                                    <f:convertDateTime pattern="dd/MMM/yyyy - hh:mm:ss a"/>
                                </h:outputLabel>
                                <br/>
                                <h:outputLabel value="Sampled : " />
                                <h:outputLabel id="lblSample" rendered="#{pi.collected}" value="#{pi.sampledAt}" >
                                    <f:convertDateTime pattern="dd/MMM/yyyy - hh:mm:ss a"/>
                                </h:outputLabel>
                                <br/>
                                <h:outputLabel value="Received : " />
                                <h:outputLabel rendered="#{pi.received}" value="#{pi.receivedAt}" >
                                    <f:convertDateTime pattern="dd/MMM/yyyy - hh:mm:ss a"/>
                                </h:outputLabel>
                                <br/>
                                <h:panelGroup rendered="#{pi.billItem.bill.cancelled}" >
                                    <h:outputLabel style="color: red;" value="Cancelled : " />
                                    <h:outputLabel style="color: red;" rendered="#{pi.billItem.bill.cancelled}" value="#{pi.billItem.bill.cancelledBill.createdAt}" >
                                        <f:convertDateTime pattern="dd/MMM/yyyy - hh:mm:ss a"/>
                                    </h:outputLabel>
                                </h:panelGroup>
                                <h:panelGroup rendered="#{pi.billItem.refunded}" >
                                    <h:outputLabel style="color: red;" value="Refunded : " />
                                    <h:outputLabel style="color: red;" rendered="#{pi.billItem.refunded}" value="#{pi.billItem.referanceBillItem.bill.createdAt}" >
                                        <f:convertDateTime pattern="dd/MMM/yyyy - hh:mm:ss a"/>
                                    </h:outputLabel>
                                </h:panelGroup>
                                <br/>
                            </p:column>
                            <p:column  headerText="Actions"  styleClass="alignTop" >
                                <p:panelGrid columns="1" rendered="#{pi.billItem.bill.cancelled ne true and pi.billItem.refunded ne true }" >
                                    <p:commandButton process="btnSample" update="tblBills"  rendered="#{!pi.collected}"   id="btnSample" value="Collect Sample" action="#{patientInvestigationController.markAsSampled}" >
                                        <f:setPropertyActionListener value="#{pi}" target="#{patientInvestigationController.current}"></f:setPropertyActionListener>
                                    </p:commandButton>
                                    <p:commandButton process="btnReceive" update="tblBills"  rendered="#{pi.received ne true}"   id="btnReceive" value="Receive Sample" action="#{patientInvestigationController.markAsReceived()}" >
                                        <f:setPropertyActionListener value="#{pi}" target="#{patientInvestigationController.current}"></f:setPropertyActionListener>
                                    </p:commandButton>
                                    <p:commandButton ajax="false" id="btnPrintWorksheets" value="Worksheet" action="/lab/single_worksheet">
                                        <f:setPropertyActionListener value="#{pi}" target="#{patientInvestigationController.current}" ></f:setPropertyActionListener>
                                    </p:commandButton>
                                    <p:commandButton ajax="false" rendered="#{pi.received}" value="Result Entry"  action="#{patientReportController.lastPatientReport(pi)}" >
                                        <f:setPropertyActionListener value="#{pi}" target="#{patientReportController.currentPtIx}"></f:setPropertyActionListener>
                                    </p:commandButton>
                                    <p:commandButton ajax="false" rendered="#{pi.received}" value="New Result" action="/lab/patient_report" actionListener="#{patientReportController.createNewReport(pi)}" >
                                        <f:setPropertyActionListener value="#{pi}" target="#{patientReportController.currentPtIx}"></f:setPropertyActionListener>
                                    </p:commandButton>
                                    <p:commandButton ajax="false" rendered="#{pi.received}" value="New Format" action="/lab/ix_for_ix" >
                                        <f:setPropertyActionListener value="#{pi}" target="#{patientReportController.currentPtIx}"></f:setPropertyActionListener>
                                        <f:setPropertyActionListener value="#{pi}" target="#{itemForItemController.patientIx}"></f:setPropertyActionListener>
                                    </p:commandButton>
                                </p:panelGrid>
                            </p:column>

                            <p:column headerText="Entered Reports"  styleClass="alignTop" >

                                <p:dataTable value="#{pi.patientReports}" var="dpr" rendered="#{pi.patientReports.size() ne 0}" >
                                    <p:column headerText="Actions">
                                        <p:commandLink style="text-decoration:underline;" value="To View / Edit / Approve / Print  " ajax="false" action="/lab/patient_report">
                                            <f:setPropertyActionListener value="#{dpr}" target="#{patientReportController.currentPatientReport}"></f:setPropertyActionListener>
                                        </p:commandLink>
                                    </p:column>
                                    <p:column headerText="Report">
                                        <h:outputLabel value="#{dpr.item.name}" >
                                        </h:outputLabel>
                                    </p:column>
                                    <p:column headerText="Data Entry at">
                                        <h:outputLabel value="#{dpr.dataEntryAt}" >
                                            <f:convertDateTime pattern="dd/MMM/yyyy - hh:mm:ss a"/>
                                        </h:outputLabel>
                                    </p:column>
                                    <p:column headerText="Approved at" >
                                        <h:outputLabel value="#{dpr.approveAt}" >
                                            <f:convertDateTime pattern="dd/MMM/yyyy - hh:mm:ss a"/>
                                        </h:outputLabel>

                                    </p:column>
                                    <p:column headerText="Printed at" >
                                        <h:outputLabel value="#{dpr.printingAt}" >
                                            <f:convertDateTime pattern="dd/MMM/yyyy - hh:mm:ss a"/>
                                        </h:outputLabel>
                                    </p:column>

                                </p:dataTable>
                            </p:column>
                        </p:dataTable>
                    </p:panel>

                </h:form>
            </ui:define>


        </ui:composition>

    </h:body>
</html>